### PR TITLE
Encode html entities in PlistToHtml parser

### LINKED ISSUE #1698: Parsing plist files into html files modifies `<string>` entries
**Describe the bug**
Parsing plist files into html files modifies `<string>` entries. For the following string:
```plist
<string> ConstraintInfo entries:

start: test.cpp:6:11 end: test.cpp:6:11
&amp;nbsp;&amp;nbsp;statement: i
&amp;nbsp;&amp;nbsp;symbol: reg_$0&lt;int i&gt;
&amp;nbsp;&amp;nbsp;constraint: 

</string>
```
This is generated
```
ConstraintInfo entries:

start: test.cpp:6:11 end: test.cpp:6:11
  statement: i
  symbol: reg_$0
  constraint: 
```
Note that `&lt;int i&gt;` is cut. Interestingly, storing doesn't seem to suffer from this issue.

**CodeChecker version**
```
------------------------------------------------------------------------
Kind                          | Version                                 
------------------------------------------------------------------------
Base package version          | 6.8.0                                   
Package build date            | 2018-07-17T17:17                        
Git commit ID (hash)          | 05a430357899df65616c21dbc9fb1327e5873cc1
Git tag information           | 6.8                                     
Configuration schema          | v6.0                                    
Database schema               | v6.0                                    
Server supported API (Thrift) | 6.11                                    
Client API (Thrift)           | 6.11                                    
------------------------------------------------------------------------
```

**To Reproduce**
```bash
# bug.plist is attached in this bugreport
CodeChecker parse bug.plist -e html -o bug.html
firefox <path to the generated html file>
```

**Expected behavior**
I would expect the bubble in the HTML output to look like this:
```
ConstraintInfo entries:

start: test.cpp:6:11 end: test.cpp:6:11
  statement: i
  symbol: reg_$0<int i>
  constraint: 
```

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: Mozilla Firefox 52.6.0

**Additional context**
I attached the plist file I'm having trouble with.
[bug.plist.zip](https://github.com/Ericsson/codechecker/files/2266701/bug.plist.zip)

### PR DESCRIPTION
**Pull request by csordasmarton**
> Closes #1698

### CODE REVIEW

File: vendor/plist_to_html/plist_to_html/dist/js/bugviewer.js [hunk 1]
```diff
@@ -10,6 +10,35 @@ var BugViewer = {
...
+
+  initEscapeChars : function () {
+    this.escapeChars = {
+      ' ' : 'nbsp',
+      '<' : 'lt',
+      '>' : 'gt',
+      '"' : 'quot',
+      '&' : 'amp',
+      '\'' : '#39'
+    };
```
Comment (gyorb) [inline vendor/plist_to_html/plist_to_html/dist/js/bugviewer.js]: Do we want to escape some other characters too?
```
    "'": '&#39;',
    '/': '&#x2F;',
    '`': '&#x60;',
    '=': '&#x3D;'
```

Comment (csordasmarton) [reply vendor/plist_to_html/plist_to_html/dist/js/bugviewer.js]: @gyorb We don't have to escape these characters. I tested it.
