### PR TITLE
Honor newlines for comments in the web GUI

### LINKED ISSUE #2259: Web GUI doesn't honor new lines for comments
**Describe the bug**
When I leave a comment at a bug report that has new lines, they aren't honored.

**CodeChecker version**
```
CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.10.0                                  
Package build date   | 2019-08-06T20:17                        
Git commit ID (hash) | 82696a802c3541de5b4ac3f0904e97b541c0793b
Git tag information  | 6.10                                    
---------------------------------------------------------------

CodeChecker web version:
------------------------------------------------------------------------
Kind                          | Version                                 
------------------------------------------------------------------------
Base package version          | 6.10.0                                  
Package build date            | 2019-08-06T20:17                        
Git commit ID (hash)          | 82696a802c3541de5b4ac3f0904e97b541c0793b
Git tag information           | 6.10                                    
Configuration schema          | v6.0                                    
Database schema               | v6.0                                    
Server supported API (Thrift) | 6.16                                    
Client API (Thrift)           | 6.16                                    
------------------------------------------------------------------------
```

**Desktop (please complete the following information)**
 - OS: ELX
 - Browser: Chrome
 - Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
http://cc.elte.hu:15001/GSoC2019-July-5/#is-unique=on&run=LLVM%2FClang%20AFTER%20tracking%20conditions%20%2B%20all%20non-control%20dependency%20changes&review-status=Confirmed&review-status=False%20positive&review-status=Intentional&detection-status=New&detection-status=Reopened&detection-status=Unresolved&tab=LLVM%2FClang%20AFTER%20tracking%20conditions%20%2B%20all%20non-control%20dependency%20changes&reportHash=8c536e75492d2588898e03178a704efb&report=49&subtab=8c536e75492d2588898e03178a704efb
image
image

### PR DESCRIPTION
**Pull request by Szelethus**
Closes #2259.

### CODE REVIEW

File: web/server/www/scripts/codecheckerviewer/CommentView.js [hunk 1]
```diff
@@ -98,7 +98,7 @@ function (declare, dom, style, topic, Memory, Observable, ConfirmDialog,
 
       this._message = new ContentPane({
         class   : 'message',
-        content : this.message
+        content : this.message.replace(/(?:\r\n|\r|\n)/g, '<br>')
```
Comment (csordasmarton) [inline web/server/www/scripts/codecheckerviewer/CommentView.js]: You have to do the same thing here:
https://github.com/Ericsson/codechecker/blob/2be579c11046ff7d119f7b4c7ee6f4803376a852/web/server/www/scripts/codecheckerviewer/CommentView.js#L136

This will be fired when you edit a comment and click on to the *Save* button.
