### PR TITLE
Fix bug tree showing all bugs in the project

### LINKED ISSUE #767: Bug list for a file showing all bugs in project & empty in diff unless Ctrl-F5
The bug list opened to a file if a single run is viewed shows **EVERY BUG EVER** in the run itself. The later added `Ctrl`-`F5` method does not solve this.

---

Concerning commit 5b5b4d8ebd8be52d783ea3d52fa841fed88c7419 (current `version6` at the time of writing this issue) if I diff two runs and take a file from the **unresolved** set, the bug list on the left side is empty.

Totally empty.
Nothing is emitted to the web browser console.

Tested diffing Xerces `3.1.1` with Xerces `3.1.2`.

Displaying _new_ and _resolved_ bugs work.
Browsing a file from a single run (and not from the diff list) **works**, even if I'm viewing the same file.

### PR DESCRIPTION
**Pull request by whisperity**
Fixes #767.

This was broken in #768. @csordasmarton Could you review this?

### CODE REVIEW

File: www/scripts/codecheckerviewer/BugViewer.js [hunk 1]
```diff
@@ -433,14 +433,15 @@ function (declare, domClass, dom, style, fx, Toggler, on, query, Memory,
         that.bugStore.put(item);
       });
 
-      var filepath = getProperFilePath(this.reportData.checkedFile);
+      var filter_file = new CC_OBJECTS.ReportFilter();
```
Comment (csordasmarton) [inline www/scripts/codecheckerviewer/BugViewer.js]: We use camel case variable names in JavaScript. Please rename it to `fileFilter`.
