### PR TITLE
HTML escaping in big viewer

### LINKED ISSUE #541: Incorrect display of a description with <>
one of the warning display the following in the code:
```
casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead
```

<cmath> is interpreted, it should be using &lt; &gt; instead

### PR DESCRIPTION
**Pull request by bruntib**
Fixes #541

### CODE REVIEW

File: viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js [hunk 1]
```diff
@@ -439,19 +440,22 @@ function (declare, dom, style, on, query, Memory, Observable, topic,
         var column = item.report.lastBugPosition.startCol;
       }
 
-      if (fileId !== this.editor.get('sourceFileData').fileId)
+      if (fileId !== this.editor.get('sourceFileData').fileId) {
```
Comment (Xazax-hun) [inline viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js]: Is this a related change? Maybe you mixed two pull requests?
