### PR TITLE
E2E tests are flaky (fix)

### LINKED ISSUE #4455: E2E tests are flaky in GitHub actions
The Firefox GUI tests in GitHub Actions are flaky right now. On Github, the tests are not non-deterministically failing (for example, https://github.com/Ericsson/codechecker/actions/runs/12867882068/job/35873440981?pr=4427 )

I have noticed a recurring theme in the errors in the GitHub job runner: Selenium reports that the click events are intercepted by an overlay element (basically, the button to be clicked is obscured).

Error message excerpt:

Error while running .clickElement() protocol action: Element <button class="confirm-btn v-btn v-btn-text themelight v-sizedefault error-text" type="button"> is not clickable at point (1045,507) because another element <div class="v-overlay__scrim"> obscures it

TimeoutError: An error occurred while running .click() command on <Section [name=removeCleanupPlanDialog],Element [name=@confirmBtn]>:
{"status":-1,"code":"","state":"element click intercepted","value":

{"additionalInformation":"\nDriver info: driver.version: unknown","localizedMessage":"Element <button class=\"confirm-btn v-btn v-btn--text theme--light v-size--default error--text\" type=\"button\"> is not clickable at point (1045,507) because another element <div class=\"v-overlay__scrim\"> obscures it\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\nSystem info: host: 'fv-az1769-515', ip: '10.1.0.7', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1074-azure', java.version: '11.0.25'\nDriver info: driver.version: unknown","systemInformation":"System info: host: 'fv-az1769-515', ip: '10.1.0.7', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1074-azure', java.version: '11.0.25'","supportUrl":null,"cause":null,"suppressed":[],"message":"Element <button class=\"confirm-btn v-btn v-btn--text theme--light v-size--default error--text\" type=\"button\"> is not clickable at point (1045,507) because another element <div class=\"v-overlay__scrim\"> obscures it\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\nSystem info: host: 'fv-az1769-515', ip: '10.1.0.7', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1074-azure', java.version: '11.0.25'\nDriver info: driver.version: unknown","class":"org.openqa.selenium.ElementClickInterceptedException","buildInformation":null}
,"errorStatus":64,"error":"Element <button class=\"confirm-btn v-btn v-btn-text themelight v-sizedefault error-text\" type=\"button\"> is not clickable at point (1045,507) because another element <div class=\"v-overlay__scrim\"> obscures it","httpStatusCode":500}
at Object.manage cleanup plans (/home/runner/work/codechecker/codechecker/web/server/vue-cli/e2e/specs/reports.js:669:29)
✖ Timed out while waiting for element <Section [name=cleanupPlanDialog],Element [name=@emptyTable]> to be visible for 5000 milliseconds. - expected "visible" but got: "not visible" (5161ms)
at Object.manage cleanup plans (/home/runner/work/codechecker/codechecker/web/server/vue-cli/e2e/specs/reports.js:672:8)

We could check if this is a timing issue (possibly by introducing delays before triggering the clicks) or something else causes this.

### PR DESCRIPTION
**Pull request by xb058t**
Fixes #4455

### CODE REVIEW

File: web/server/vue-cli/e2e/specs/reports.js [hunk 1]
```diff
@@ -279,9 +279,15 @@ module.exports = {
     reportPage.expect.section(dateDialog).to.be.visible.before(5000);
     reportPage.expect.element("@overlay").to.be.visible.before(5000);
 
-    dateDialog
```
Comment (dkrupp) [inline web/server/vue-cli/e2e/specs/reports.js:282]: Please leave this code block here commented out with the note that that this would have been the ideal way, but due to the overlay it was unreliable and maybe a TODO, to change this back afte Vue3 update.

You don't need this comment at all the other places, the simple removal can remain.

**Review by dkrupp — CHANGES_REQUESTED** [review]
Please leave in comment why do we need this workaround and a todo that we should revisit this after vue3 update.

**Review by dkrupp — APPROVED** [review]
LGTM
