### PR TITLE
[docker] Fix running docker container with existing volume

### LINKED ISSUE #3458: docker-compose fails to run CodeChecker server with permission denied
**Describe the bug**
docker-compose files that mount a workspace volume to /workspace will create that directory when the service container is created. That directory will always have owner root. The entrypoint.sh script will see that the /workspace directory exists and not run `chown codechecker` on it. However, `CodeChecker server` when run as user codechecker needs to be the owner of /workspace to write to it.

**CodeChecker version**
v6.17.0

**To Reproduce**
Run `docker-compose up` on any of the [sample files](https://github.com/Ericsson/codechecker/tree/master/web/docker/services). You may need to change the image to `codechecker/codechecker-web:v6.17.0` 

**Expected behaviour**
codechecker service should initialize correctly.

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: N/A
 - Version: N/A

**Additional context**
None.

### LINKED ISSUE #3525: docker server with postgres, root.user missed
**Describe the bug**
I cloned the repository, then `make package` as the manual indicates, after that `docker build -t codechecker-web:latest web/docker` executes well but when I tried `docker-compose -f web/docker/services/docker-compose.psql.yml` it has the following error:
```
Traceback (most recent call last):
codechecker_1  |   File "/codechecker/lib/python3/codechecker_common/cli.py", line 206, in main
codechecker_1  |     sys.exit(args.func(args))
codechecker_1  |   File "/codechecker/lib/python3/codechecker_server/cmd/server.py", line 435, in __handle
codechecker_1  |     main(args)
codechecker_1  |   File "/codechecker/lib/python3/codechecker_server/cmd/server.py", line 1008, in main
codechecker_1  |     server_init_start(args)
codechecker_1  |   File "/codechecker/lib/python3/codechecker_server/cmd/server.py", line 986, in server_init_start
codechecker_1  |     environ)
codechecker_1  |   File "/codechecker/lib/python3/codechecker_server/server.py", line 972, in start_server
codechecker_1  |     root_sha = __make_root_file(root_file)
codechecker_1  |   File "/codechecker/lib/python3/codechecker_server/server.py", line 948, in __make_root_file
codechecker_1  |     with open(root_file, 'w', encoding="utf-8", errors="ignore") as f:
codechecker_1  | PermissionError: [Errno 13] Permission denied: '/workspace/root.user'
services_codechecker_1 exited with code 1
```
What I have tried next was create the `root.user` file empty with execution-read-write permissions, in a ./workspace directory, but the error persists, would you help me?

**CodeChecker version**
6.19.0 

**To Reproduce**
`docker-compose -f web/docker/services/docker-compose.psql.yml`

**Expected behaviour**
The server running a postgres database

**Desktop (please complete the following information)**
Ubuntu 20.04

### PR DESCRIPTION
**Pull request by csordasmarton**
> Closes #3525 and closes #3458

- Print some useful info message in the `entrypoint.sh` script file.
- If the `workspace` directory already exists when the container started, try
to run the given command with the owner of the workspace directory, otherwise
run it with the `codechecker` user.

### CODE REVIEW

**Review by whisperity — COMMENTED** [review]
In general I'm not sure whether we should print these to the standard error, though.

File: web/docker/entrypoint.sh [hunk 1]
```diff
@@ -6,24 +6,34 @@ WORKSPACE_DIR="/workspace"
...
 
-  # Execute this script again with codechecker user.
-  exec gosu codechecker "$0" "$@"
+    echo "Execute script again with 'codechecker' user."
+    exec gosu codechecker "$0" "$@"
+  fi
 fi
 
-# Set PostgreSQL password file from secrets.
 pgpass=/run/secrets/pgpass
```
[the remark this answers is not in the document]
Comment (csordasmarton) [reply web/docker/entrypoint.sh:31]: This is a docker specific secret file which is automatically mounted to this directory when secrets are used. We have an example for this use case here: 
https://github.com/Ericsson/codechecker/blob/40273a8d26c6d897a3e68fe55d51a85716d4a00b/web/docker/services/docker-compose.swarm.yml#L43-L44

File: web/docker/entrypoint.sh [hunk 2]
```diff
@@ -1,29 +1,41 @@
...
+    echo "Creating workspace directory: '${WORKSPACE_DIR}'."
+    echo "WARNING: This directory exists ONLY within the containter!"
+
     mkdir -p $WORKSPACE_DIR
     chown -R codechecker:codechecker $WORKSPACE_DIR
-  fi
 
-  # Execute this script again with codechecker user.
-  exec gosu codechecker "$0" "$@"
+    echo "Executing script with internal 'codechecker' user (UID: $USER_ID)..."
```
Comment (whisperity) [inline web/docker/entrypoint.sh:26]:
```
$ docker run codechecker-web:csordasmarton/fix_docker_entry_point --help
Container started with 'root' user.
Creating workspace directory: '/workspace'.
WARNING: This directory exists ONLY within the containter!
Executing script with internal 'codechecker' user (UID: 0)...
Executing command: '--help'.
exec: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
```

I think here you shouldn't say `$USER_ID`, but `$(id -u codechecker)`? Because this line is executed **before** the `exec` call.

File: web/docker/entrypoint.sh [hunk 3]
```diff
@@ -1,29 +1,41 @@
...
+    exec gosu codechecker "$0" "$@"
```
Comment (whisperity) [inline web/docker/entrypoint.sh:27]: Does this exec do something meaningful? `$0` should start the `entrypoint.sh` script again, no?

I was expecting the following output:

```
Started with root
Creating dir
Executing with internal user ...
(self-call begins here)
Started with internal user
Executing command CodeChecker blah...
```

But instead, I got this:

```
$ docker run codechecker-web:csordasmarton/fix_docker_entry_point
Container started with 'root' user.
Creating workspace directory: '/workspace'.
WARNING: This directory exists ONLY within the containter!
Executing script with internal 'codechecker' user (UID: 0)...
Executing command: 'CodeChecker server --workspace /workspace --not-host-only'.
[INFO 2021-12-08 11:20] - Checking configuration database ...
```

But the process is running with the right userid (950).

File: web/docker/entrypoint.sh [hunk 4]
```diff
@@ -1,29 +1,41 @@
...
+if [ "$USER_ID" = '0' ]; then
+  echo "Container started with 'root' user."
+
+  if [ -d $WORKSPACE_DIR ]; then
+    echo "Workspace directory '${WORKSPACE_DIR}' already exists."
+
+    workspace_dir_owner=$(stat ${WORKSPACE_DIR} -c %u)
+    if [ "${workspace_dir_owner}" != '0' ]; then
+      echo "Executing script with workspace directory owner (UID): '${workspace_dir_owner}'..."
+      exec gosu $workspace_dir_owner "$0" "$@"
```
Comment (whisperity) [inline web/docker/entrypoint.sh:17]: Thanks, can confirm this works!

```
$ docker run -v $(readlink -f workspace):/workspace codechecker-web:csordasmarton/fix_docker_entry_point
Container started with 'root' user.
Workspace directory '/workspace' already exists.
Executing script with workspace directory owner (UID): '1000'...
Executing command: 'CodeChecker server --workspace /workspace --not-host-only'.
[INFO 2021-12-08 11:25] - Checking configuration database ...
```

```
$ ls -alh
/home/whisperity/CodeChecker/web/docker/workspace
Permissions Size User    Date Modified Name
.rw-r--r--   57k whisperity  8 Dec 12:25  config.sqlite
.rw-r--r--  209k whisperity  8 Dec 12:25  Default.sqlite
.r--------    71 whisperity  8 Dec 12:25  root.user
.rw-r--r--  1,6k whisperity  8 Dec 12:25  server_config.json
```

File: web/docker/entrypoint.sh (hunk 2 above)
Comment (csordasmarton) [reply web/docker/entrypoint.sh]: Good catch, fixed it.

File: web/docker/entrypoint.sh (hunk 3 above)
Comment (csordasmarton) [reply web/docker/entrypoint.sh:27]: Yes, we will start the enrypoint again. In the second time what we will print is only the `Executing command: ...` message and the logs of the started process. Other logs are printed when the container is started with the root user.

Comment (whisperity) [reply web/docker/entrypoint.sh:27]: Ah... gotcha! Yeah because the `Container started with 'root' user.` is hardcoded and printed ONLY if we are root, it is not a generic message that prints the current username in *every* case.

Alright.

**Review by whisperity — APPROVED** [review]
