### PR TITLE
[analyzer] Fix plist file name collision

### LINKED ISSUE #2435: .plist filename collision
[case.zip](https://github.com/Ericsson/codechecker/files/3869276/case.zip)

**Source files with equal filename (not path) generates and overwrites the filename.plist result file during analysis step**

Filename hash generation don't include the buildaction directory.

**CodeChecker version**
You can get version info by running `CodeChecker version`:
---------------------------------------------------------------
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.10.1                                  
Package build date   | 2019-11-20T13:20                        
Git commit ID (hash) | 76d1ea88faa9467563a7dc1ce28d2b03ee77c5d7
Git tag information  | 6.10.1                                  
---------------------------------------------------------------

CodeChecker web version:
------------------------------------------------------------------------
Kind                          | Version                                 
------------------------------------------------------------------------
Base package version          | 6.10.1                                  
Package build date            | 2019-11-20T13:20                        
Git commit ID (hash)          | 76d1ea88faa9467563a7dc1ce28d2b03ee77c5d7
Git tag information           | 6.10.1                                  
Server supported API (Thrift) | 6.20                                    
Client API (Thrift)           | 6.20                                    
------------------------------------------------------------------------

**To Reproduce**
unzip case.zip
./test.sh

**Expected behavior**
What you expected to happen.
...[
INFO 2019-11-20 13:51] - See --help and the user guide for further options about parsing and storing the reports.
[INFO 2019-11-20 13:51] - ----=================----
[INFO 2019-11-20 13:51] - Analysis length: 0.631727933884 sec.
4  <----- EXPECTED   but ACTUAL : 2

i
**Desktop (please complete the following information)**
 - OS: linux
 - Browser NaN
 - Version NaN

**Additional context**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by csordasmarton**
> Closes #2435 

Source files with equal filename generates and overwrites the
filename.plist result file during analysis step. The main problem
is that the filename hash generation contains only the filename and
not the file path.
This commit will solve this problem and include the buildaction
directory (removes the users home directory from the path) to the
filename hash.

### CODE REVIEW

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/CodeChecker/codechecker/pullRequest?prid=4623413&bid=15502631)

File: analyzer/tests/functional/analyze_and_parse/test_files/filename_collision/a/f.cpp [hunk 1]
```diff
@@ -0,0 +1,4 @@
+void f_a() {
+    int* pa;
+    *pa = 42;
```
Comment (gyorb) [inline analyzer/tests/functional/analyze_and_parse/test_files/filename_collision/a/f.cpp]: Codacy Issue found: [Uninitialized variable: pa](https://app.codacy.com/app/CodeChecker/codechecker/pullRequest?prid=4623413)

File: analyzer/tests/functional/analyze_and_parse/test_files/filename_collision/b/f.cpp [hunk 2]
```diff
@@ -0,0 +1,4 @@
+void f_b() {
+    int* pb;
+    *pb = 42;
```
Comment (gyorb) [inline analyzer/tests/functional/analyze_and_parse/test_files/filename_collision/b/f.cpp]: Codacy Issue found: [Uninitialized variable: pb](https://app.codacy.com/app/CodeChecker/codechecker/pullRequest?prid=4623413)

File: analyzer/tests/functional/analyze_and_parse/test_files/filename_collision/a/f.cpp [hunk 3]
```diff
@@ -0,0 +1,4 @@
+void f_a() {
+    int* pa;
```
Comment (gyorb) [inline analyzer/tests/functional/analyze_and_parse/test_files/filename_collision/a/f.cpp]: Codacy Issue found: [Variable 'pa' is not assigned a value.](https://app.codacy.com/app/CodeChecker/codechecker/pullRequest?prid=4623413)

File: analyzer/tests/functional/analyze_and_parse/test_files/filename_collision/b/f.cpp [hunk 4]
```diff
@@ -0,0 +1,4 @@
+void f_b() {
+    int* pb;
```
Comment (gyorb) [inline analyzer/tests/functional/analyze_and_parse/test_files/filename_collision/b/f.cpp]: Codacy Issue found: [Variable 'pb' is not assigned a value.](https://app.codacy.com/app/CodeChecker/codechecker/pullRequest?prid=4623413)

File: analyzer/codechecker_analyzer/analyzers/result_handler_base.py [hunk 5]
```diff
@@ -90,10 +90,18 @@ def analyzer_result_file(self):
         if not self.__result_file:
             analyzed_file_name = os.path.basename(self.analyzed_source_file)
 
-            build_info = str(self.buildaction.analyzer_type) + '_' + \
+            source_file = os.path.normpath(
+                os.path.join(self.buildaction.directory,
+                             self.analyzed_source_file))
+
+            source_file = os.path.relpath(source_file,
```
Comment (Xazax-hun) [inline analyzer/codechecker_analyzer/analyzers/result_handler_base.py]: Why are we creating a relative path from the user's home directory?

Comment (gamesh411) [inline analyzer/codechecker_analyzer/analyzers/result_handler_base.py]: Wouldn't it be possible to simply use the absolute path of the source file for the hash? I mean, if the collision is because of the same basename of files, and we add the user-home to that, it would be still not unique. And if the uniqueness is ensured later, this expansion is redundant IMHO.

**Comment by gyorb** [comment]
@csordasmarton do you have any comments on the review results?

**Comment by csordasmarton** [comment]
@gyorb I rebased and fixed my commit based on the review comments.

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=4623413&bid=15502631)
