### PR TITLE
Fix run deletion in GUI

### LINKED ISSUE #2234: Impossible to delete run in the web GUI
when selecting the run to detete i get the following js error
Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
flush @ thrift.js:348
ObjectStore.js:19 Uncaught TypeError: Cannot read property 'get' of undefined
    at Object.getValue (ObjectStore.js:19)
    at Object.<anonymous> (DataGrid.js:15)
    at dojo.js:15
    at ObjectStore.js:145
    at Function.when (dojo.js:15)
    at Object.fetchItemByIdentity (ObjectStore.js:143)
    at Object.doApplyCellEdit (DataGrid.js:15)
    at Object.applyCellEdit (DataGrid.js:15)
    at Object.applyStaticValue (DataGrid.js:15)
    at Object.doclick (DataGrid.js:15)
getValue @ ObjectStore.js:19
(anonymous) @ DataGrid.js:15
(anonymous) @ dojo.js:15
(anonymous) @ ObjectStore.js:145
when @ dojo.js:15
fetchItemByIdentity @ ObjectStore.js:143
doApplyCellEdit @ DataGrid.js:15
applyCellEdit @ DataGrid.js:15
applyStaticValue @ DataGrid.js:15
doclick @ DataGrid.js:15
dispatchEvent @ DataGrid.js:15
dispatchEvent @ DataGrid.js:15
dispatchContentEvent @ DataGrid.js:15
onContentEvent @ DataGrid.js:15
doContentEvent @ DataGrid.js:15
(anonymous) @ dojo.js:15

### PR DESCRIPTION
**Pull request by bruntib**
- typo: run.runId -> run.runid.
- Missing get() function for the storage object.
- run.runid is not an array.
- checkbox should be checked even if its cell is clicked.
- The deleteRunIds array should be cleared in the async callback
  function otherwise it will see an empty array by that time it runs.

Fixes #2234

### CODE REVIEW

File: web/server/www/scripts/codecheckerviewer/ListOfRuns.js [hunk 1]
```diff
@@ -92,7 +92,24 @@ function (declare, dom, ObjectStore, Store, Deferred, topic, Dialog, Button,
...
+      var runFilter = new CC_OBJECTS.RunFilter();
+      runFilter.ids = [ id ];
+
+      CC_SERVICE.getRunData(runFilter, 1, 0, function (runDataList) {
+        if (typeof runDataList === 'string') {
+          deferred.reject('Failed to get run ' + id + ': ' + runDataList);
+        } else {
+          deferred.resolve(runDataList[0]);
+        }
+      }).fail(function (xhr) { util.handleAjaxFailure(xhr); });
```
Comment (gyorb) [inline web/server/www/scripts/codecheckerviewer/ListOfRuns.js]: Shouldn't we call the deferred.reject in the fail section too, and provide some additional error message to the user that the run removal failed? What if the delete query times out?

Comment (bruntib) [reply web/server/www/scripts/codecheckerviewer/ListOfRuns.js]: There is a ticket for fixing this at every occurrence: #2257.
