### PR TITLE
[fix] Pass `envp` to `posix_spawn` in `ld_logger`

### LINKED ISSUE #3860: «log» sometimes does not put in "file": the subpath
I call
```console
$ CodeChecker log -b "make" -o json.json &> cc-log-out
```
Then cc-log-out contains:
```
make[2]: Entering directory '/git/productname/something/src/abcxyz'
mkdir -p /git/productname/something/obj-g/abcxyzb0.dll/unix
g++  -c -DLINUX -Dlinux -fPIC -DPIC -DTATRA_OFFSET -I.  -I/git/productname/something/src/include  -I/git/productname/something/src/unix/include -m32 -DUSE_FFI  -fprofile-arcs -ftest-coverage -pg -g -DDEBUG -D_DEBUG  -I. -Dunix  -D_UNIX_ -DUNIX   -DSTRICT  -o /git/productname/something/obj-g/abcxyzb0.dll/unix/tatra.o /git/productname/something/src/abcxyz/unix/tatra.cpp

/git/productname/something/unix/custom_link_command /git/productname/something/lib-g/abcxyzb0.dll  /git/productname/something/obj-g/abcxyzb0.dll/abcxyz.def -m32 -fprofile-arcs -ftest-coverage  -ldl -lpthread  [… many .o files …] /git/productname/something/obj-g/abcxyzb0.dll/unix/tatra.o  -L/git/productname/something/lib-g -L/git/productname/something/lib-g
make[2]: Leaving directory '/git/productname/something/src/abcxyz'
```
custom_link_command calls c++.  Despite having «dll» this is all Linux  code.  Then `json.json` includes:
```json
{
         "directory": "/git/productname/something/src/abcxyz",
         "command": "/usr/libexec/gcc/x86_64-redhat-linux/12/cc1plus  -quiet -I . -I /git/productname/something/src/include -I 
/git/productname/something/src/unix/include -I . -imultilib 32 -D_GNU_SOURCE -D LINUX -D linux -D PIC -D TATRA_OFFSET -D USE_FFI -D DEBUG -D _DEBUG -D unix -D _UNIX_ -D UNIX -D STRICT  /git/productname/something/src/abcxyz/unix/tatra.cpp -quiet -dumpdir /git/productname/something/obj-g/abcxyzb0.dll/unix/ -dumpbase tatra.cpp  -dumpbase-ext .cpp -m32 -mtune=generic -march=i686 -g -p -fPIC -fprofile-arcs -ftest-coverage -o /tmp/ccfnhb0i.s",
         "file": "/git/productname/something/src/abcxyz/unix/tatra.cpp"
}
,
{
         "directory": "/git/productname/something/src/abcxyz",
         "command": "/usr/libexec/gcc/x86_64-redhat-linux/12/cc1plus -quiet -I . -I /git/productname/something/src/include -I 
/git/productname/something/src/unix/include -I . -imultilib 32 -D_GNU_SOURCE -D LINUX -D linux -D PIC -D TATRA_OFFSET -D USE_FFI -D DEBUG -D _DEBUG -D unix -D _UNIX_ -D UNIX -D STRICT  /git/productname/something/src/abcxyz/unix/tatra.cpp -quiet -dumpdir /git/productname/something/obj-g/abcxyzb0.dll/unix/ -dumpbase tatra.cpp -dumpbase-ext .cpp -m32 -mtune=generic -march=i686 -g -p -fPIC -fprofile-arcs -ftest-coverage -o /tmp/ccfnhb0i.s",
         "file": "tatra.cpp"
}
```
As next I execute «CodeChecker analyze json.json --analyzers clangsa --ctu --z3-refutation on -o x123», which runs in parallel.  It 
complains:
```
[INFO 2023-03-15 16:28] - [71/372] tatra.cpp
… text cut …
[INFO 2023-03-15 16:28] - [82/372] tatra.cpp
[INFO 2023-03-15 16:28] - [83/372] file.cpp
[ERROR 2023-03-15 16:28] - Error generating AST.

command:

/usr/local/bin/clang-15 -c -x c++ -I /git/productname/something/src/abcxyz -I  /git/productname/something/src/include -I 
/git/productname/something/src/unix/include -I /git/productname/something/src/abcxyz -D_GNU_SOURCE -D LINUX -D linux -D 
 PIC -D TATRA_OFFSET -D USE_FFI -D DEBUG -D _DEBUG -D unix -D _UNIX_ -D UNIX -D STRICT -m32 -mtune=generic -march=i686 -fPIC -fprofile-arcs -ftest-coverage -isystem /usr/include/c++/12 -isystem  /usr/include/c++/12/x86_64-redhat-linux -isystem 
/usr/include/c++/12/backward -isystem /usr/local/include -isystem /usr/include /git/productname/something/src/abcxyz/tatra.cpp -std=gnu++17 -emit-ast -D__clang_analyzer__ -w -o /git/productname/something/unix/x123/ctu-dir/ast/git/productname/something/src/abcxyz/tatra.cpp.ast

stderr:

clang-15: error: no such file or directory: 
'/git/productname/something/src/abcxyz/tatra.cpp'
clang-15: error: no input files

[ERROR 2023-03-15 16:28] - Error generating function map.

command:

/usr/local/bin/clang-extdef-mapping  /git/productname/something/src/abcxyz/tatra.cpp -- -c -x c++ -I 
/git/productname/something/src/abcxyz -I /git/productname/something/src/include -I /git/productname/something/src/unix/include -I /git/productname/something/src/abcxyz -D_GNU_SOURCE -D LINUX -D linux -D  PIC -D TATRA_OFFSET -D USE_FFI -D DEBUG -D _DEBUG -D unix -D _UNIX_ -D UNIX -D STRICT -m32 -mtune=generic -march=i686 -fPIC -fprofile-arcs  -ftest-coverage -isystem /usr/include/c++/12 -isystem /usr/include/c++/12/x86_64-redhat-linux -isystem  /usr/include/c++/12/backward -isystem /usr/local/include -isystem /usr/include -std=gnu++17

stderr:

error: no such file or directory: 
'/git/productname/something/src/abcxyz/tatra.cpp'
error: no input files
error: unable to handle compilation, expected exactly one compiler job 
in ''
Error while processing /git/productname/something/src/abcxyz/tatra.cpp.
```

The problem report is, that for "directory": "/git/productname/something/src/abcxyz" “log” creates two files:

"file": "/git/productname/something/src/abcxyz/unix/tatra.cpp" and
"file": "tatra.cpp"

but these are supposed to be the same file.  In particular  /git/productname/something/src/abcxyz/tatra.cpp does not exist.

I use the latest codechecker (git commit eac25bc82a91ea91b963d768e3c0b7aae6022cbe ) compiled from source and I  run codechecker within its virtualevn (created by «make venv»).

### PR DESCRIPTION
**Pull request by bruntib**
GNU make 4.3 uses posix_spawn() for initiating recursive make calls in subdirectories:

make -C &lt;subdirectory&gt;

Since we overwrote posix_spawn() through LD_PRELOAD and we didn't forward environment variables to the subprocess, the build of the submodule didn't get the environment variables set by a Makefile. This commit fixes this issue so the logging phase behaves the same way as the original build.

Fixes #3860

### CODE REVIEW

File: analyzer/tools/build-logger/src/ldlogger-hooks.c [hunk 1]
```diff
@@ -46,19 +46,12 @@
     the program to execute, so we're not reusing CC_LOGGER_CALL_EXEC.          \
   */                                                                           \
   tryLog(path, argv);                                                          \
-  /*                                                                           \
-    Note that envp is not passed through (which would be the environment that  \
-    that the process will be spawned it), but is replaced by environ, which is \
-    a global variable that stores our environment. We added quite a few        \
-    variables into it, and for some reason, they are not present in envp.      \
-  */                                                                           \
```
Comment (Szelethus) [inline analyzer/tools/build-logger/src/ldlogger-hooks.c:54]: It was a while since I wrote this, but I recall that some codechecker (`CC_*`) and logger related variables were not present in envp, but should've been. Can you verify thats not an issue?

Comment (bruntib) [reply analyzer/tools/build-logger/src/ldlogger-hooks.c:54]: I'm not sure, which environment variable was involved in your case, but this function call blocked the forwarding of all environment variable. I assume, this `cc_` was among them too.

**Review by whisperity — CHANGES_REQUESTED** [review]
Can you add a test for this?

Something along the lines of a Makefile which calls `gcc ${ENVIRONMENT_VARIABLE}` and a `/usr/bin/env ENVIRONMENT_VARIABLE=foo.cpp CodeChecker log -b "make"`?

**Review by whisperity — APPROVED** [review]
